server:
  port: 8081

spring:
  datasource:
    username: root
    password: 980710
    url: jdbc:mysql://localhost:3306/oolitemall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: xmu.good.oomall.domain
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com:
      example:
        mapper : debug